#!/bin/sh
#fix the doc path
#PACK_LOCATION="$1"
#INST_LOCATION="$3"
#"$PACK_LOCATION/Contents/Resources/qtconf.pl" -version $VERSION_MAJOR$.$VERSION_MINOR$ -value "$INST_LOCATION/Developer/Applications/Qt/plugins" Plugins
