#!/bin/sh

# We need to do things differently on different platforms
# <10.3.9 Can't install
# =10.3.9 Can install, but must check license manually
# >=10.4 Just jump out

os_version=`sysctl kern.osrelease | awk '{ print $3 }'`
os_major=`echo $os_version | cut -d . -f 1`
os_minor=`echo $os_version | cut -d . -f 2`

if [ $os_major -lt 7 -o $os_major -eq 7 -a $os_minor -lt 9 ]; then
    exit $((96+19))
elif [ $os_major -eq 7 -a $os_minor -eq 9 ]; then
    [ -f $HOME/.qt-license ] || exit $((96+16));

    . $HOME/.qt-license >/dev/null 2>&1
    [ -z "$LicenseKeyExt" -o -z "$Licensee" ] && exit $((96+17))

    grep "Evaluation" "$1/Contents/Resources/Welcome.rtf" 2>&1 >/dev/null && LicenseType="Evaluation" || LicenseType="Commercial"

    # License key format is incorrect.
    echo $LicenseKeyExt | grep ".....*-....*-....*-....*-.....*-.....*-...." 2>&1 >/dev/null  || exit $((96+17)) 

    #Test the key is correct.
    productTest=`echo $LicenseKeyExt | cut -f 1 -d - | cut -b 1`
    platformTest=`echo $LicenseKeyExt | cut -f 2 -d - | cut -b 1`
    licenseFeatureTest=`echo $LicenseKeyExt | cut -f 4 -d - | cut -b 1`
    licenseTypeTest=`echo $LicenseKeyExt | cut -f 3 -d - | cut -b 1`

    case $productTest in
    F)
    # Universal
    ProductType="Universal"
    ;;
    B)
    # Desktop
    ProductType="Desktop"
    ;;
    L)
    # Desktop Lite
    ProductType="Desktop Light"
    ;;
    R)
    # Console
    ProductType="Console"
    ;;
    *)
    exit $((96+18)) ;;
    esac

    #check the palatform.
    case $platformTest in
    4|L|5|G|Y|2|F|B)
    # Qt/Mac
    ;;
    *)
    exit $((96+18)) ;;
    esac

    case $licenseTypeTest in
    F|T|3)
        licenseTest=Commercial
        ;;
    Z|R|Q)
        licenseTest=Evaluation
        ;;
    *)
        ;;
    esac

    [ "$licenseTest" != "$LicenseType" ] && exit $((96+18))

    expiryDate=`"$1/Contents/Resources/keydecoder" $LicenseKeyExt | sed -e s,-,,g`
    if [ -z "$expiryDate" ]; then
        exit $((96+18))
    fi

    packageDate=`cat "$1/Contents/Resources/.package_date" | sed -e s,-,,g`
    today=`date +%Y%m%d`

    case $licenseTest in
    Commercial)
        if [ $packageDate -gt $expiryDate ]; then
            exit $((96+20))
        fi
        ;;
    Evaluation)
        if [ $today -gt $expiryDate ]; then
            exit $((96+21))
        fi
        ;;
    esac
fi

exit 0
