######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 15:16:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

QT = core network

include(../../src/src.pri)

# Input
SOURCES += main.cpp


