######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 26 13:53:24 2006
######################################################################

TEMPLATE = app
TARGET = tst_qstylesheetstyle
DEPENDPATH += .
INCLUDEPATH += . ..

CONFIG += console qtestlib
contains(QT_CONFIG, qt3support): QT += qt3support

# Input
SOURCES += tst_qstylesheetstyle.cpp
RESOURCES += resources.qrc
