######################################################################
# Automatically generated by qmake (2.01a) fr 26. sep 13:21:57 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
HEADERS += qpropertytransform.h
CONFIG  += console

