######################################################################
# Automatically generated by qmake (2.01a) fr 13. feb 13:26:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

CONFIG += console