######################################################################
# Automatically generated by qmake (2.01a) fr 15. mai 08:51:37 2009
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += layoutitem.h widgetchooserdelegate.h window.h scene.h
FORMS += anchorlayout.ui
SOURCES += layoutitem.cpp main.cpp widgetchooserdelegate.cpp window.cpp scene.cpp

DEFINES += PRO_FILE_PWD=$$_PRO_FILE_PWD_