######################################################################
# Automatically generated by qmake (2.01a) mer. 21. janv. 13:53:26 2009
######################################################################

TEMPLATE = app
QT += phonon
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

RESOURCES = sound.qrc

# Input
SOURCES += main.cpp
