/****************************************************************************
**
** Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
** All rights reserved.
** Contact: Nokia Corporation (qt-info@nokia.com)
**
** This file is part of the examples of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:LGPL$
** No Commercial Usage
** This file contains pre-release code and may not be distributed.
** You may use this file in accordance with the terms and conditions
** contained in the Technology Preview License Agreement accompanying
** this package.
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain additional
** rights.  These rights are described in the Nokia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** If you have questions regarding the use of this file, please contact
** Nokia at qt-info@nokia.com.
**
**
**
**
**
**
**
**
** $QT_END_LICENSE$
**
**
** This file was generated by qdbusxml2cpp version 0.7
** Command line was: qdbusxml2cpp -i car_adaptor.h -a :car_adaptor.cpp car.xml
**
** qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
**
** This is an auto-generated file.
** Do not edit! All changes made to it will be lost.
**
****************************************************************************/

#include "car_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarInterfaceAdaptor
 */

CarInterfaceAdaptor::CarInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarInterfaceAdaptor::~CarInterfaceAdaptor()
{
    // destructor
}

void CarInterfaceAdaptor::accelerate()
{
    // handle method call com.trolltech.Examples.CarInterface.accelerate
    QMetaObject::invokeMethod(parent(), "accelerate");
}

void CarInterfaceAdaptor::decelerate()
{
    // handle method call com.trolltech.Examples.CarInterface.decelerate
    QMetaObject::invokeMethod(parent(), "decelerate");
}

void CarInterfaceAdaptor::turnLeft()
{
    // handle method call com.trolltech.Examples.CarInterface.turnLeft
    QMetaObject::invokeMethod(parent(), "turnLeft");
}

void CarInterfaceAdaptor::turnRight()
{
    // handle method call com.trolltech.Examples.CarInterface.turnRight
    QMetaObject::invokeMethod(parent(), "turnRight");
}

