<ListModel>
    <Contact>
        <firstName>Aaron</firstName>
        <lastName>Kennedy</lastName>
        <portrait>contact.png</portrait>
        <emails>
            <Email address="akennedy@trolltech.com"/>
            <Email address="aaron.kennedy@trolltech.com"/>
        </emails>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>1</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>2</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>3</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>4</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>5</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>6</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>7</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>8</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Contact</firstName>
        <lastName>9</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Alan</firstName>
        <lastName>Alpert</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Betty</firstName>
        <lastName>Boo</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Foo</firstName>
        <lastName>Bar</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Marius</firstName>
        <lastName>Bugge Monsen</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Martin</firstName>
        <lastName>Jones</lastName>
        <portrait>contact.png</portrait>
        <emails>
            <Email address="mjones@trolltech.com"/>
            <Email address="martin.jones@trolltech.com"/>
        </emails>
    </Contact>
    <Contact>
        <firstName>Michael</firstName>
        <lastName>Brasser</lastName>
        <portrait>contact.png</portrait>
        <emails>
            <Email address="mbrasser@trolltech.com"/>
        </emails>
    </Contact>
    <Contact>
        <firstName>Yann</firstName>
        <lastName>Bodson</lastName>
        <portrait>contact.png</portrait>
    </Contact>
    <Contact>
        <firstName>Yogi</firstName>
        <lastName>Bear</lastName>
        <portrait>contact.png</portrait>
    </Contact>
</ListModel>
