######################################################################
# Automatically generated by qmake (2.01a) Tue May 4 13:36:26 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += declarative

# Input
SOURCES += main.cpp
RESOURCES += layoutItem.qrc
