######################################################################
# Automatically generated by qmake (2.01a) on 22. apr 14:11:33 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += C:/dev/kinetic/examples/statemachine/errorstate/. .

# Input
HEADERS += mainwindow.h plugin.h tank.h tankitem.h
SOURCES += main.cpp mainwindow.cpp tankitem.cpp
CONFIG += console
