######################################################################
# Automatically generated by qmake (1.08a) Mon Oct 18 13:59:36 2004
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qev.cpp
CONFIG += qt warn_on create_prl link_prl
