######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 2 20:15:52 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
