######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 17:07:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += console
include(../../src/src.pri)
# Input
QT = core network

SOURCES += main.cpp


