######################################################################
# Automatically generated by qmake (2.01a) ma 22. jan 10:10:16 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += src\main.cpp

TRANSLATIONS = ts\project.ts


!exists(ts) {
    win32: system(md ts)
    else: system(mkdir ts)
}
