######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 29 22:24:47 2006
######################################################################

load(qttest_p4)
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -framework Carbon

HEADERS += qnativeinput.h qnativeplayer.h
SOURCES += qnativeinput.cpp qnativeplayer.cpp qnativeinput_mac.cpp

SOURCES += tst_macnativeevents.cpp

requires(mac)
