######################################################################
# Automatically generated by qmake (2.01a) ven. 22. août 13:09:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
           river.cpp \
           riveritem.cpp \
           menu.cpp
HEADERS += river.h \
           riveritem.h \
           menu.h 
