<!--
ListModel allows free form list models to be defined and populated.
Be sure to name the file the same as the id.
-->
<ListModel id="MyPetsModel">
    <Pet>
        <name>Rover</name>
        <type>Dog</type>
        <age>5</age>
    </Pet>
    <Pet>
        <name>Whiskers</name>
        <type>Cat</type>
        <age>2</age>
    </Pet>
    <Pet>
        <name>Warren</name>
        <type>Rabbit</type>
        <age>2</age>
    </Pet>
    <Pet>
        <name>Polly</name>
        <type>Parrot</type>
        <age>12</age>
    </Pet>
    <Pet>
        <name>Spot</name>
        <type>Dog</type>
        <age>9</age>
    </Pet>
    <Pet>
        <name>Tiny</name>
        <type>Elephant</type>
        <age>15</age>
    </Pet>
    <Pet>
        <name>Penny</name>
        <type>Turtle</type>
        <age>4</age>
    </Pet>
    <Pet>
        <name>Joey</name>
        <type>Kangaroo</type>
        <age>1</age>
    </Pet>
    <Pet>
        <name>Kimba</name>
        <type>Bunny</type>
        <age>65</age>
    </Pet>
</ListModel>
