#!/usr/bin/env python

import os, sys, shutil, re

def readLicenseFile():
    licenseKeyPath = os.path.join(os.environ['HOME'], '.qt-license');
    
    licenseKeyRE = re.compile(r"^LicenseKeyExt=(.+)$")
    license = open(licenseKeyPath, 'r')
    licensekey = "Bad Key"
    for line in license:
        matchObj = licenseKeyRE.match(line)
        if matchObj:
            licensekey = matchObj.group(1) 
    return licensekey

def getEditionDefine():
    licenseKey = readLicenseFile()
    
    MeteredMap = { '5': True, 'L': True }

    if len(licenseKey) == 0:
       return false

    licenseParts = licenseKey.split('-')
    return MeteredMap.get(licenseParts[3][0], False)


if __name__ == "__main__":
    if getEditionDefine() == False:
        usageReporterPath = os.path.join(os.path.sep, 'usr', 'bin', 'qtusagereporter')
        reporterInDevToolsPath = os.path.join(os.path.sep, 'Developer', 'Tools', 'qtusagereporter')
        if os.path.exists(usageReporterPath):
            finalPath = os.path.realpath(usageReporterPath);
            os.remove(finalPath)
            if os.path.exists(reporterInDevToolsPath):
                os.remove(reporterInDevToolsPath)
            if os.path.exists(usageReporterPath):
                os.remove(usageReporterPath)
    sys.exit(0)
