######################################################################
# Automatically generated by qmake (2.01a) to 2. okt 23:22:11 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h animation.h
SOURCES += main.cpp window.cpp

FORMS   += form.ui

RESOURCES     = resources.qrc
