QT += core script
TARGET = testgen
CONFIG += console
CONFIG -= app_bundle
TEMPLATE = app

SOURCES += main.cpp \
    testgenerator.cpp
HEADERS += testgenerator.h


INPUT_DATASET = data.txt
dataset.name = Generating QScraiptValue autotest's dataset
dataset.output = autogenerated.cpp
dataset.commands = python gen.py data.txt autogenerated.cpp
dataset.input = INPUT_DATASET
dataset.variable_out = SOURCES
QMAKE_EXTRA_COMPILERS += dataset
