######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 11 17:18:17 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imagewidget.h
SOURCES += imagewidget.cpp main.cpp
