.TH "qtconfig" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
qtconfig \- Configuration tool for Qt
.SH "DESCRIPTION"
.LP 
QConfig allows for GUI based configuration of Qt and
 other Qt based sources.

.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBQTDIR\fP
Specifies the base Qt dir
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
.TH "qtconfig" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
qtconfig \- Configuration tool for Qt
.SH "DESCRIPTION"
.LP 
QConfig allows for GUI based configuration of Qt and
 other Qt based sources.

.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBQTDIR\fP
Specifies the base Qt dir
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
