######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 19 12:58:26 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
!contains(QT_CONFIG,dbus): {
    DEFINES += QT_NO_DBUS
}
