######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 16:11:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += object1.h object2.h object3.h object4.h object5.h object6.h object7.h
SOURCES += main.cpp
